import type { Metadata } from "next";
import "./globals.css";
import {
  NavBar,
  Footer,
  Page,
  Grid,
  Feature,
  Teaser,
  Testimonial,
  MenuLink,
  Config,
  Hero,
  Projects,
} from "components";
import { apiPlugin, storyblokInit } from "@storyblok/react/rsc";
const cachedFetch = (
  input: string | Request | URL,
  init?: RequestInit
): Promise<Response> => {
  return fetch(input, {
    ...init,
    cache: "no-store",
  });
};
// Initialize Storyblok
storyblokInit({
  accessToken: process.env.STORYBLOK_TOKEN,
  use: [apiPlugin],
  components: {
    feature: Feature,
    grid: Grid,
    page: Page,
    teaser: Teaser,
    testimonial: Testimonial,
    navbar: NavBar,
    menu_link: MenuLink,
    footer: Footer,
    hero: Hero,
    projects: Projects,
  },
  apiOptions: {
    fetch: cachedFetch,
  },
});

export const metadata: Metadata = {
  title: "Vofs website",
  description: "Generated by create next app",
};
interface RootLayoutProps {
  children: React.ReactNode;
}
export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        //max-w-[1140px] mx-auto
        className="bg-default-blue text-white"
        suppressHydrationWarning={true}
      >
        <Config />
        {children}
        <Footer />
      </body>
    </html>
  );
}
