import type { Metadata } from "next";
import "./globals.css";
import { NavBar, Footer } from "components";
import { Page, Grid, Feature, Teaser, Testimonial } from "components";
import { apiPlugin, storyblokInit } from "@storyblok/react/rsc";

const cachedFetch = (input: any, init?: any): Promise<Response> => {
  return fetch(input, {
    ...init,
    cache: "no-store",
  });
};
// Initialize Storyblok
storyblokInit({
  accessToken: process.env.STORYBLOK_TOKEN,
  use: [apiPlugin],
  components: {
    feature: Feature,
    grid: Grid,
    page: Page,
    teaser: Teaser,
    testimonial: Testimonial,
  },
  apiOptions: {
    fetch: cachedFetch,
  },
});

export const metadata: Metadata = {
  title: "Vofs website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className="bg-default-blue text-white"
        suppressHydrationWarning={true}
      >
        {/* <NavBar /> */}
        {children}

        {/* <Footer /> */}
      </body>
    </html>
  );
}
